name: PDF Importer - Build and deploy

on:
  push:
    branches:
      - "main"
    paths:
      - 'green_app/**'
  workflow_dispatch:

jobs:
  publish-test:
    defaults:
      run:
        working-directory: ./green_app
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GH_TOKEN }}
          persist-credentials: false

      - name: 📦 Deploy
        run: ../deploy.sh
        env:
          PITCHER_API_KEY: ${{ secrets.PITCHER_API_KEY }}
          PITCHER_INSTANCE_ID: ${{ secrets.PITCHER_INSTANCE_ID }}
          PITCHER_DOMAIN: ${{ secrets.PITCHER_DOMAIN }}
